### PR TITLE
Add an automatic upload of results to the production support server

### PR DESCRIPTION
**Pull request by njezersek**

### CODE REVIEW

**Review by themarpe — CHANGES_REQUESTED** [review]
Reference to `depthai-boards` instead of having a copy of files here

**Review by themarpe — CHANGES_REQUESTED** [review]
`add_result` seems to not be called?

**Review by themarpe — APPROVED** [review]
LGTM

**Comment by njezersek** [comment]
Tested with the following devices:
- OAK-D-Pro-FF
- OAK-D-Pro-W
- OAK-D-SR
- OAK-D-Pro-PoE-AF

**Pull request merged**
